name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Suparadu.Claude.ClientApi/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - 'Suparadu.Claude.ClientApi/**'

env:
  NODE_VERSION: 20
  APP_LOCATION: "./Suparadu.Coin.Web"
  OUTPUT_LOCATION: "dist/suparadu.coin.web/browser"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Check Node.js version
        run: node --version
      - name: Update npm
        run: npm install -g npm@latest
      - name: Output angular.json
        run: cat angular.json
        working-directory: ${{ env.APP_LOCATION }}
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_LOCATION }}
      - name: Build application
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}
      - name: List dist contents
        run: |
          echo "Contents of dist folder:"
          ls -R dist
          echo "Contents of dist/suparadu.coin.web/browser folder:"
          ls -R dist/suparadu.coin.web/browser
        working-directory: ${{ env.APP_LOCATION }}
      - name: Find index.html
        run: find dist -name index.html
        working-directory: ${{ env.APP_LOCATION }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          negativeFunctionKey: ${{ secrets.negativeFunctionKey }}
          azureFunctionUrl: ${{ secrets.azureFunctionUrl }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_RIVER_09744CA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ""
          output_location: ${{ env.OUTPUT_LOCATION }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_RIVER_09744CA03 }}
          action: "close"