name: Build and deploy Suparadu.Claude.ClientApi to Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'Suparadu.Claude.ClientApi/**'
      - '.github/workflows/main_suparadu-coin-claude-client-api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Suparadu.Claude.ClientApi/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'suparadu-coin-claude-client-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Suparadu.Claude.ClientApi'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.5.0
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5A6815D4628A4641A9F75FE618E859CA }}
